# Generated by Django 3.0.9 on 2020-10-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
